package com.project.helpcircle.domain.model

/**
 * A locally-stored recap of one weekly cycle, generated by the lazy weekly-reset check.
 * [agencyIndexDelta] is this device's own IA_ind trend across the week — the community's IA_comm
 * itself is never persisted locally (only fetched live from Firestore), so there's no local
 * history to compute a true community-wide trend from.
 */
data class WeeklySummary(
    val weekStartEpochMillis: Long,
    val agencyIndexDelta: Int,
    val mostEffectiveInterventionCategory: String?,
    val peakCrisisHour: Int?
)
